version: '3'
services:
  abb-discord-bot:
    image: ghcr.io/drmxrcy/abb-discord-bot:latest
    container_name: abb-discord-bot
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt:/mnt
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    user: "1000:1000"