version: "3"
services:
  abb-discord-bot:
    restart: unless-stopped
    container_name: abb-discord-bot
    image: ghcr.io/drmxrcy/abb-discord-bot:latest
    hostname: abb-discord-bot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
    volumes:
      - /opt/abb-discord-bot:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt
    env_file:
      - .env

networks:
  saltbox:
    external: true 