name: Create Release and Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get current date
        id: date
        run: echo "RELEASE_NAME=UPDATE - $(date +'%B %d, %Y')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Latest
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          files: |
            docker-compose.yml
            example.env

  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="abb-discord-bot"
          DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          DOCKERHUB_REPO="abb-discord-bot"

          # Build the Docker image
          docker build -t $IMAGE_NAME .

          # Tag the Docker image
          docker tag $IMAGE_NAME $DOCKERHUB_USERNAME/$DOCKERHUB_REPO

          # Push the Docker image to DockerHub
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO